web:
  image: kyonmm/nginx-dynamic-custom:0.1
  volumes:
   - ./mysite.template:/etc/nginx/conf.d/mysite.template
  ports:
   - "8081:81"
  environment:
   - NGINX_PORT=81
  command: # <1>
    /bin/ash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"